#!/usr/bin/env python3
# tools/scan-weak-items.py
# Read-only report: scans every EXISTING weapon/armor/shield in the game
# (including items generated by gen-missing-items.py, which will simply
# never be flagged since they're already calibrated) and flags ones whose
# combat power looks disproportionately weak for their owning zone's
# level/remort tier, using the same mob_fix.c-anchored calibration as
# gen-missing-items.py. Writes nothing -- prints a report only.
#
# Usage: python3 tools/scan-weak-items.py [--threshold 0.5]

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OBJ_DIR = os.path.join(ROOT, 'wdii', 'lib', 'world', 'obj')
AREAS_PATH = os.path.join(ROOT, 'web', 'assets', 'data', 'areas.json')
MOBFIX_TABLE_PATH = os.path.join(ROOT, 'tools', 'mobfix-table.json')

with open(MOBFIX_TABLE_PATH) as f:
    MOBFIX_TABLE = json.load(f)

with open(AREAS_PATH) as f:
    AREAS = {a['vnum']: a for a in json.load(f)}


def mob_dam_avg(level):
    level = max(0, min(210, round(level)))
    row = MOBFIX_TABLE[level]
    ndice, sdice, extra = row[5], row[6], row[7]
    return ndice * (sdice + 1) / 2.0 + extra


def level_midpoint(level_str):
    nums = re.findall(r'\d+', str(level_str))
    if not nums:
        return 100.0
    nums = [int(n) for n in nums]
    return sum(nums) / len(nums)


def effective_level(zone_vnum):
    area = AREAS.get(zone_vnum)
    if not area:
        return None
    mid = level_midpoint(area['level'])
    return max(0.0, min(210.0, mid + area.get('remort', 0) * 8)), area['name'], area.get('remort', 0), area['level']


def read_index():
    with open(os.path.join(OBJ_DIR, 'index')) as f:
        return [l.strip() for l in f if l.strip() and not l.strip().startswith('$')]


def parse_all_items():
    items = []  # (vnum, fname, lines)
    for fn in read_index():
        path = os.path.join(OBJ_DIR, fn)
        with open(path, 'rb') as f:
            c = f.read().decode('latin-1')
        blocks = re.split(r'\n(?=#\d+\n)', c)
        for b in blocks:
            lines = b.strip('\n').split('\n')
            if not lines or not lines[0].startswith('#'):
                continue
            try:
                vnum = int(lines[0][1:])
            except ValueError:
                continue
            items.append((vnum, fn, lines))
    return items


def find_numline_idx(lines):
    tcount = 0
    for i, l in enumerate(lines):
        if l.endswith('~'):
            tcount += 1
            if tcount == 4:
                return i + 1
    return None


def main():
    threshold = 0.5
    if '--threshold' in sys.argv:
        threshold = float(sys.argv[sys.argv.index('--threshold') + 1])

    items = parse_all_items()
    weak_weapons = []
    weak_armor = []
    skipped_no_zone = 0

    for vnum, fname, lines in items:
        numline_idx = find_numline_idx(lines)
        if numline_idx is None or numline_idx >= len(lines):
            continue
        numline = lines[numline_idx].split()
        if not numline:
            continue
        type_flag = numline[0]
        zone_vnum = vnum // 100
        eff_info = effective_level(zone_vnum)
        if eff_info is None:
            skipped_no_zone += 1
            continue
        eff, zname, remort, level_str = eff_info
        short_desc = lines[2][:55] if len(lines) > 2 else '?'

        if type_flag == '5':  # weapon
            if numline_idx + 1 >= len(lines):
                continue
            valline = lines[numline_idx + 1].split()
            if len(valline) < 3:
                continue
            try:
                ndice, sdice = int(valline[1]), int(valline[2])
            except ValueError:
                continue
            avg = ndice * (sdice + 1) / 2.0
            damroll = 0
            for i, l in enumerate(lines):
                if l == 'A' and i + 1 < len(lines):
                    p = lines[i + 1].split()
                    if len(p) == 2 and p[0] == '19':
                        damroll = int(p[1])
            total = avg + damroll * 0.8
            expected_floor = mob_dam_avg(eff) * 0.35  # weakest sane tier used by the generator
            if total < expected_floor * threshold and expected_floor > 3:
                ratio = total / expected_floor if expected_floor else 0
                weak_weapons.append((ratio, vnum, fname, short_desc, total, expected_floor, zname, level_str, remort))

        elif type_flag == '9':  # armor / shield
            if numline_idx + 1 >= len(lines):
                continue
            valline = lines[numline_idx + 1].split()
            if not valline:
                continue
            try:
                value0_ac = int(valline[0])
            except ValueError:
                continue
            # apply_ac() (handler.c) multiplies value0 by a slot factor
            # (BODY=3x, HEAD/LEGS=2x, else 1x) -- approximate with 1x here
            # since wear slot isn't tracked in this scan; this only affects
            # the ranking order slightly, not the presence of a real bonus.
            # Older/pre-existing items instead often carry a direct
            # "A / 17 <negative>" APPLY_AC affect (no value0, no slot
            # factor) -- both mechanisms are real and functional in this
            # engine, so combine them into one comparable score.
            ac17_bonus = 0
            for i, l in enumerate(lines):
                if l == 'A' and i + 1 < len(lines):
                    p = lines[i + 1].split()
                    if len(p) == 2 and p[0] == '17':
                        m = int(p[1])
                        if m < 0:
                            ac17_bonus += -m
            effective_ac = value0_ac + ac17_bonus
            expected_floor = max(1, (1 + eff / 15 * 0.5) * 0.35 / 0.7)  # rough common-tier floor
            if effective_ac < expected_floor * threshold and expected_floor > 1.5:
                ratio = effective_ac / expected_floor if expected_floor else 0
                weak_armor.append((ratio, vnum, fname, short_desc, effective_ac, expected_floor, zname, level_str, remort))

    weak_weapons.sort(key=lambda r: r[0])
    weak_armor.sort(key=lambda r: r[0])

    print(f"=== WEAK WEAPONS (total dmg < {threshold*100:.0f}% of zone floor) ===")
    print(f"{len(weak_weapons)} found\n")
    for ratio, vnum, fname, name, total, floor, zname, level_str, remort in weak_weapons[:60]:
        print(f"  [{ratio:.2f}x floor] vnum {vnum} ({fname}) '{name}' -- dmg {total:.1f} vs floor {floor:.1f} | zone: {zname} (lvl {level_str}, r{remort})")

    print(f"\n=== WEAK ARMOR/SHIELDS (AC < {threshold*100:.0f}% of zone floor) ===")
    print(f"{len(weak_armor)} found\n")
    for ratio, vnum, fname, name, ac, floor, zname, level_str, remort in weak_armor[:60]:
        print(f"  [{ratio:.2f}x floor] vnum {vnum} ({fname}) '{name}' -- AC {ac} vs floor {floor:.1f} | zone: {zname} (lvl {level_str}, r{remort})")

    print(f"\n(skipped {skipped_no_zone} items owned by zones with no areas.json entry)")


if __name__ == '__main__':
    main()
